/*
 * Decompiled with CFR 0.152.
 */
package net.minecraft.client.statistics;

import java.util.ArrayList;
import java.util.List;
import net.minecraft.a.a.b.C_x;
import net.minecraft.a.b.Item;
import net.minecraft.a.b.ItemStack;
import net.minecraft.client.statistics.Achievement;
import net.minecraft.client.statistics.AchievementDisplay;
import net.minecraft.client.statistics.CategoryDisplay;
import net.minecraft.client.statistics.IAchieveDisplay;

public class AchievementList {
    public static final List<Achievement> achievementList = new ArrayList<Achievement>();
    public static final List<Achievement> challengeList = new ArrayList<Achievement>();
    public static final Achievement openInventory = new Achievement(0, "Taking Inventory", "Use the achievements as a guide!", Item.book, null).registerAchievement();
    public static final Achievement getWood = new Achievement(1, "Timber!", "Get a block of wood from a tree", C_x.y, openInventory);
    public static final Achievement buildWorkBench = new Achievement(2, "Benched", "Use planks to craft a workbench", C_x.an, getWood);
    public static final Achievement buildChest;
    public static final Achievement restInBed;
    public static final Achievement buildJukebox;
    public static final Achievement buildPickaxe;
    public static final Achievement buildFurnace;
    public static final Achievement charcoal;
    public static final Achievement acquireIron;
    public static final Achievement buildGenerator;
    public static final Achievement useTNT;
    public static final Achievement silkTouch;
    public static final Achievement emeralds;
    public static final Achievement diamonds;
    public static final Achievement buildHoe;
    public static final Achievement seeds;
    public static final Achievement compost;
    public static final Achievement fertilize;
    public static final Achievement makeBread;
    public static final Achievement bakePie;
    public static final Achievement buildFishingRod;
    public static final Achievement cookFish;
    public static final Achievement killFish;
    public static final Achievement wrangleMob;
    public static final Achievement fishBucket;
    public static final Achievement buildSword;
    public static final Achievement killEnemy;
    public static final Achievement buildBattleAxe;
    public static final Achievement buildSpear;
    public static final Achievement buildQuiver;
    public static final Achievement armor;
    public static final Achievement fireArrow;
    public static final Achievement moonTerraform;
    public static final Achievement fungus;
    public static final Achievement hellIce;
    public static final Achievement cloud;
    public static final Achievement bounce;
    public static final Achievement spong;
    public static final Achievement reducePoison;
    public static final Achievement bloodMoon;
    public static final Achievement killGiant;
    public static final Achievement buildLantern;
    public static final Achievement hellfireLighter;
    public static final Achievement endChest;
    public static final Achievement buildCharm;
    public static final Achievement buildPortal;
    public static final Achievement colorPortal;
    public static final Achievement crossbow;
    public static final Achievement lightTorch;
    public static final Achievement cobblestone;
    public static final Achievement onARail;
    public static final Achievement diet;
    public static final Achievement ripoff;
    public static final Achievement snipeSkeleton;
    public static final Achievement killGiantSpecial;
    public static final Achievement killImpSpecial;
    public static final Achievement killHarpySpecial;
    public static final Achievement killAntlionSpecial;
    public static final Achievement yearChallenge;
    public static final Achievement adventure;
    public static final Achievement slayer;
    public static final Achievement recipes;
    public static final Achievement scoring;
    public static final Achievement trophy;
    public static final List<IAchieveDisplay> achieveDisplayList;
    public static final List<IAchieveDisplay> challengeDisplayList;

    public static void init() {
    }

    static {
        buildPickaxe = new Achievement(6, "Time to Mine!", "Craft a pickaxe", Item.p, buildWorkBench);
        buildFurnace = new Achievement(7, "Hot Topic", "Craft a furnace using cobblestone", C_x.ar, buildPickaxe);
        acquireIron = new Achievement(9, "Acquire Hardware", "Smelt raw iron in a furnace", Item.k, buildFurnace);
        emeralds = new Achievement(13, "Ooo! Shiny!", "Mine emeralds using an iron pick", Item.emerald, acquireIron);
        diamonds = new Achievement(14, "DIAMONDS!", "Mine diamonds using an emerald pick", Item.j, emeralds);
        fireArrow = new Achievement(45, "Bullseye!", "Hit a mob with a dart", Item.dartShooter, emeralds);
        bloodMoon = new Achievement(41, "Bloodbath", "Witness a blood moon", Item.pearl, (Achievement)null);
        killGiant = new Achievement(42, "Giant Slayer", "Slay a giant during a blood moon", Item.ingotAdminium, bloodMoon);
        buildLantern = new Achievement(43, "Advanced Lighting", "Craft a permanent light source", C_x.lantern, killGiant);
        hellfireLighter = new Achievement(44, "Efficient Smelting", "Smelt something with hellfire", Item.f, killGiant);
        endChest = new Achievement(48, "Dimensional Delivery", "Make an adminium chest", C_x.chest, killGiant);
        buildCharm = new Achievement(49, "Constructing Trinkets", "Craft and equip a charm item", Item.ring, killGiant);
        buildPortal = new Achievement(68, "Brave New World", "Light a portal with hellfire", C_x.ae, hellfireLighter);
        colorPortal = new Achievement(47, "Color Your World", "Throw a dye item in a portal", Item.dyePowder, buildPortal);
        crossbow = new Achievement(69, "Lock and Load", "Load up a crossbow", Item.crossbowLoaded, killGiant);
        lightTorch = new Achievement(31, "Let There Be Light!", "Re-light a torch using a lighter", C_x.af, bloodMoon);
        achieveDisplayList = new ArrayList<IAchieveDisplay>();
        challengeDisplayList = new ArrayList<IAchieveDisplay>();
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.GENERAL));
        achieveDisplayList.add(new AchievementDisplay(getWood.setCategory(Achievement.Category.GENERAL).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(buildWorkBench.setCategory(Achievement.Category.GENERAL).registerAchievement()));
        buildChest = new Achievement(3, "Storage Central", "Make barrel for portable storage", C_x.barrel, buildWorkBench).setCategory(Achievement.Category.GENERAL).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildChest));
        restInBed = new Achievement(5, "Speedy Recovery", "Rest in a bed to recover health", Item.bed, buildWorkBench).setCategory(Achievement.Category.GENERAL).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(restInBed));
        buildJukebox = new Achievement(4, "In the Groove!", "Play a music disc in a jukebox", C_x.jukeBox, diamonds).setCategory(Achievement.Category.GENERAL).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildJukebox));
        achieveDisplayList.add(new AchievementDisplay(lightTorch.setCategory(Achievement.Category.GENERAL).registerAchievement()));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.MINING));
        achieveDisplayList.add(new AchievementDisplay(buildPickaxe.setCategory(Achievement.Category.MINING).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(buildFurnace.setCategory(Achievement.Category.MINING).registerAchievement()));
        charcoal = new Achievement(8, "Renewable Energy", "Produce a piece of charcoal", new ItemStack(Item.i, 1, 1), buildFurnace).setCategory(Achievement.Category.MINING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(charcoal));
        achieveDisplayList.add(new AchievementDisplay(acquireIron.setCategory(Achievement.Category.MINING).registerAchievement()));
        buildGenerator = new Achievement(10, "Industrial Revolution", "Craft and power a generator", C_x.generator, acquireIron).setCategory(Achievement.Category.MINING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildGenerator));
        useTNT = new Achievement(11, "Boom!", "Make and trigger some TNT", C_x.ab, buildPickaxe).setCategory(Achievement.Category.MINING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(useTNT));
        silkTouch = new Achievement(12, "Silky Smooth", "Craft any golden tool", Item.E, acquireIron).setCategory(Achievement.Category.MINING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(silkTouch));
        achieveDisplayList.add(new AchievementDisplay(emeralds.setCategory(Achievement.Category.MINING).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(diamonds.setCategory(Achievement.Category.MINING).registerAchievement()));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.FARMING));
        buildHoe = new Achievement(15, "Time to Farm!", "Craft a hoe", Item.J, buildWorkBench).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildHoe));
        seeds = new Achievement(16, "A Seedy Place", "Use a hoe on grass for seeds", Item.O, buildHoe).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(seeds));
        compost = new Achievement(70, "Green Thumb", "Make some fertilizer in a composter", C_x.composter, seeds).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(compost));
        fertilize = new Achievement(17, "They Grow Up So Fast!", "Use fertilizer to grow something", Item.fertilizer, compost).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(fertilize));
        makeBread = new Achievement(18, "Bake Bread", "Make bread using wheat", Item.Q, seeds).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(makeBread));
        bakePie = new Achievement(19, "A Delicious Treat", "Have a slice of apple pie", Item.cake, seeds).setCategory(Achievement.Category.FARMING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(bakePie));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.FISHING));
        buildFishingRod = new Achievement(20, "Time to Fish!", "Craft a fishing rod", Item.fishingRod, buildWorkBench).setCategory(Achievement.Category.FISHING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildFishingRod));
        cookFish = new Achievement(21, "Delicious Fish", "Catch and cook a fish", Item.fishCooked, buildFishingRod).setCategory(Achievement.Category.FISHING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(cookFish));
        killFish = new Achievement(22, "Fishy Business", "Fish up a fin with your rod", Item.fishFin, buildFishingRod).setCategory(Achievement.Category.FISHING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(killFish));
        wrangleMob = new Achievement(23, "Nice Catch!", "Wrangle a mob with a fishing rod", Item.G, buildFishingRod).setCategory(Achievement.Category.FISHING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(wrangleMob));
        fishBucket = new Achievement(30, "Tactical Fishing", "Catch a fish without a fishing rod", Item.bucketFish, cookFish).setCategory(Achievement.Category.FISHING).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(fishBucket));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.COMBAT));
        buildSword = new Achievement(24, "Time to Strike!", "Craft a sword", Item.n, buildWorkBench).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildSword));
        buildBattleAxe = new Achievement(25, "Striking Harder!", "Hit 3+ mobs with a charged attack", Item.battleAxeIron, buildSword).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildBattleAxe));
        buildSpear = new Achievement(26, "Long and Pointy!", "Craft and throw a spear at a mob", Item.spearStone, buildSword).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildSpear));
        achieveDisplayList.add(new AchievementDisplay(fireArrow.setCategory(Achievement.Category.COMBAT).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(crossbow.setCategory(Achievement.Category.COMBAT).registerAchievement()));
        buildQuiver = new Achievement(27, "Ammo Pouch", "Equip a quiver for more arrows", Item.quiver, buildSword).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(buildQuiver));
        armor = new Achievement(28, "Matching Attire", "Equip a full suit of armor", Item.S, buildSword).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(armor));
        killEnemy = new Achievement(29, "Monster Hunter", "Slay a monster", Item.bone, buildSword).setCategory(Achievement.Category.COMBAT).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(killEnemy));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.ADVENTURE));
        achieveDisplayList.add(new AchievementDisplay(colorPortal.setCategory(Achievement.Category.ADVENTURE).registerAchievement()));
        moonTerraform = new Achievement(35, "Terraforming the Moon", "Bring grass to the moon", C_x.moonRock, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(moonTerraform));
        fungus = new Achievement(36, "Fungus Amongus", "Fertilize shrooms in a normal world", C_x.mycelium, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(fungus));
        hellIce = new Achievement(37, "Hell Frozen Over", "Produce water in a hell world", C_x.ice, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(hellIce));
        cloud = new Achievement(38, "Smooth Landing", "Land on a cloud after a long fall", C_x.cloudBlock, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(cloud));
        bounce = new Achievement(39, "Sticky Situation", "Bounce on a slime block", C_x.slimeBlock, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(bounce));
        spong = new Achievement(40, "Who lives under the sea?", "Smelt some coral into sponge", C_x.A, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(spong));
        reducePoison = new Achievement(67, "Antidote", "Safely swim in infested waters", Item.vial, colorPortal).setCategory(Achievement.Category.ADVENTURE).registerAchievement();
        achieveDisplayList.add(new AchievementDisplay(reducePoison));
        achieveDisplayList.add(new CategoryDisplay(Achievement.Category.ENDGAME));
        achieveDisplayList.add(new AchievementDisplay(bloodMoon.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(killGiant.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(buildLantern.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(hellfireLighter.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(endChest.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(buildCharm.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        achieveDisplayList.add(new AchievementDisplay(buildPortal.setCategory(Achievement.Category.ENDGAME).registerAchievement()));
        challengeDisplayList.add(new CategoryDisplay(Achievement.Category.GENERAL));
        cobblestone = new Achievement(50, "Got Cobble?", "Mine 3,456 stone blocks", C_x.l, buildPickaxe).setSpecial().setCategory(Achievement.Category.GENERAL).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(cobblestone));
        onARail = new Achievement(53, "On A Rail", "Travel 1,000 blocks in a minecart", C_x.rail, acquireIron).setSpecial().setCategory(Achievement.Category.GENERAL).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(onARail));
        ripoff = new Achievement(51, "Serious Dedication", "Fully use up a diamond hoe", Item.M, diamonds).setSpecial().setCategory(Achievement.Category.GENERAL).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(ripoff));
        diet = new Achievement(62, "A Balanced Diet", "Eat every type of food", Item.B, bakePie).setSpecial().setCategory(Achievement.Category.GENERAL).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(diet));
        challengeDisplayList.add(new CategoryDisplay(Achievement.Category.COMBAT));
        snipeSkeleton = new Achievement(54, "Sniper Duel", "Kill a skeleton from 30 blocks away", Item.g, killEnemy).setSpecial().setCategory(Achievement.Category.COMBAT).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(snipeSkeleton));
        killGiantSpecial = new Achievement(55, "Skilled", "Slay a giant with a golden weapon", Item.C, killGiant).setSpecial().setCategory(Achievement.Category.COMBAT).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(killGiantSpecial));
        killImpSpecial = new Achievement(56, "Stay Frosty!", "Defeat a fire imp with snowballs", Item.snowball, killEnemy).setSpecial().setCategory(Achievement.Category.COMBAT).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(killImpSpecial));
        killHarpySpecial = new Achievement(57, "Air Combat", "Destroy a harpy while gliding", Item.bootsHermes, killEnemy).setSpecial().setCategory(Achievement.Category.COMBAT).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(killHarpySpecial));
        killAntlionSpecial = new Achievement(58, "Whack-a-mole", "Kill an antlion while it is buried", Item.c, killEnemy).setSpecial().setCategory(Achievement.Category.COMBAT).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(killAntlionSpecial));
        challengeDisplayList.add(new CategoryDisplay(Achievement.Category.ENDGAME));
        yearChallenge = new Achievement(59, "How Did We Get Here?", "Survive for 100 days in a world", Item.bookAndQuill, (Achievement)null).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(yearChallenge));
        adventure = new Achievement(60, "Adventure Time!", "Visit every portal dimension", Item.ag, colorPortal).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(adventure));
        slayer = new Achievement(61, "Ultimate Slayer", "Kill every mob at least once", Item.v, killEnemy).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(slayer));
        recipes = new Achievement(63, "Researcher", "Unlock all recipes", Item.paper, buildWorkBench).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(recipes));
        scoring = new Achievement(64, "New Highscore!", "Reach a score of 100,000", Item.l, killEnemy).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(scoring));
        trophy = new Achievement(65, "Number One", "Do all achievements and challenges", Item.bracelet, (Achievement)null).setSpecial().setCategory(Achievement.Category.ENDGAME).registerAchievement();
        challengeDisplayList.add(new AchievementDisplay(trophy));
        System.out.println(achievementList.size() + " achievements");
        System.out.println(challengeList.size() + " challenges");
    }
}

